
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_DEBUG_MODULE_DEVICE_ID,
		XPAR_DEBUG_MODULE_BASEADDR,
		XPAR_DEBUG_MODULE_BAUDRATE,
		XPAR_DEBUG_MODULE_USE_PARITY,
		XPAR_DEBUG_MODULE_ODD_PARITY,
		XPAR_DEBUG_MODULE_DATA_BITS
	},
	{
		XPAR_RS232_UART_1_DEVICE_ID,
		XPAR_RS232_UART_1_BASEADDR,
		XPAR_RS232_UART_1_BAUDRATE,
		XPAR_RS232_UART_1_USE_PARITY,
		XPAR_RS232_UART_1_ODD_PARITY,
		XPAR_RS232_UART_1_DATA_BITS
	}
};


